#!/bin/sh

LABEL=$1
GIT_SHA=$(git rev-parse HEAD)

docker build --build-arg GIT_SHA=$GIT_SHA -t $ECR_DOMAIN/saloonbot/saloonbot-server -f Dockerfile.server .
docker build --build-arg GIT_SHA=$GIT_SHA -t $ECR_DOMAIN/saloonbot/saloonbot-bot -f Dockerfile.bot .
