services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=saloonbot
      - MYSQL_USER=saloonbot
      - MYSQL_PASSWORD=saloonbot_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  mysql_data:
