services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_DB=saloonbot
      - POSTGRES_USER=saloonbot
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-saloonbot}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres_data:

