name: Docker Image CI

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./Dockerfile.bot
            image: ghcr.io/markrcote/saloonbot-bot
          - dockerfile: ./Dockerfile.server
            image: ghcr.io/markrcote/saloonbot-server

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - name: Check out repo
      uses: actions/checkout@v5

    - name: Log into the container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ matrix.image }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ${{ matrix.dockerfile }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
